# Generated by Django 3.2.13 on 2022-07-27 09:50

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='email')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('last_login', models.DateTimeField(auto_now_add=True, verbose_name='Date de la dérnière connexion')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('tel', models.CharField(blank=True, max_length=60, null=True)),
                ('role', models.CharField(blank=True, choices=[('Responsable', 'Responsable'), ('Agent', 'Agent')], max_length=100, null=True)),
                ('prenom', models.CharField(blank=True, max_length=30, null=True, verbose_name='Prénom')),
                ('nom', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nom')),
                ('photo', models.ImageField(blank=True, default=authentication.models.get_default_profile_image, max_length=255, null=True, upload_to=authentication.models.get_profile_image_filepath)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', authentication.models.MyAccountManager()),
            ],
        ),
    ]
