# Generated by Django 3.2.13 on 2022-07-27 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=50)),
                ('type', models.CharField(choices=[('Hopital', 'Hopital'), ('Clinique', 'Clinique'), ('Pharmacie', 'Pharmacie')], default='Clinique', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=50)),
                ('dateNaissance', models.DateField()),
                ('age', models.IntegerField(default=0)),
                ('sexe', models.CharField(blank=True, max_length=10, null=True)),
                ('proffesion', models.CharField(blank=True, max_length=255, null=True)),
                ('groupSanguin', models.CharField(blank=True, max_length=10, null=True)),
                ('photo', models.ImageField(blank=True, default=home.models.get_default_profile_image, max_length=255, null=True, upload_to=home.models.get_profile_image_filepath)),
                ('docteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.entite')),
            ],
        ),
        migrations.CreateModel(
            name='Radio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('photo', models.ImageField(blank=True, max_length=255, null=True, upload_to=home.models.get_radio_image_filepath)),
                ('docteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.patients')),
            ],
        ),
        migrations.CreateModel(
            name='DossierPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('diagnostic', models.TextField(blank=True, null=True)),
                ('traitement', models.TextField(blank=True, null=True)),
                ('docteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.entite')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.patients')),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('responsable', models.CharField(max_length=50)),
                ('entite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.entite')),
            ],
        ),
        migrations.CreateModel(
            name='Antecedant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('titre', models.CharField(blank=True, max_length=20, null=True)),
                ('antecedant', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.patients')),
            ],
        ),
    ]
