# Generated by Django 3.2.13 on 2022-07-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossierpatient',
            name='paiement',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
