# Generated by Django 3.1.14 on 2022-10-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20220729_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossierpatient',
            name='dateRV',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
