# Generated by Django 4.1.3 on 2022-11-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_dossierpatient_remarques'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossierpatient',
            name='paiement',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
