# Generated by Django 4.1.3 on 2022-12-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_testdossierpatient_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdossierpatient',
            name='nom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testdossierpatient',
            name='prenom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
